### ISSUE TITLE
Soldering -Station / Modified.ino

### ISSUE THREAD

**Issue by giorgio-palma** [ManojBR105/Soldering-Station#1]
I've been trying to compile the sketch for a long time "
Modified.ino "(for display 1602) with the following arduino IDE version:
1.6.2
1.6.3
1.8.8 IDE
but the code gives me a compilation error.
You can help me??

**Comment by DeshmukhMalhar** [comment]
can you post the error when arduino's verbose mode is enabled ?

**Comment by giorgio-palma** [comment]
This is the error when compiling the "Modified.ino" code:
Arduino: 1.8.8 (Windows 8.1), Board: "Arduino Nano, ATmega328"

C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\GIORGIOP\AppData\Local\Arduino15\packages -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\GIORGIOP\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\GIORGIOP\Documents\Arduino\libraries -fqbn=arduino:avr:nano:cpu=atmega328 -ide-version=10808 -build-path C:\Users\GIORGIOP\AppData\Local\Temp\arduino_build_808351 -warnings=none -build-cache C:\Users\GIORGIOP\AppData\Local\Temp\arduino_cache_141 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=C:\Users\GIORGIOP\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.0.1-arduino2 -prefs=runtime.tools.avrdude-6.0.1-arduino2.path=C:\Users\GIORGIOP\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.0.1-arduino2 -prefs=runtime.tools.avr-gcc.path=C:\Users\GIORGIOP\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino2 -prefs=runtime.tools.avr-gcc-4.8.1-arduino2.path=C:\Users\GIORGIOP\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino2 -verbose C:\Users\GIORGIOP\AppData\Local\Temp\arduino_modified_sketch_540121\sketch_jan25a.ino
C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\GIORGIOP\AppData\Local\Arduino15\packages -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\GIORGIOP\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\GIORGIOP\Documents\Arduino\libraries -fqbn=arduino:avr:nano:cpu=atmega328 -ide-version=10808 -build-path C:\Users\GIORGIOP\AppData\Local\Temp\arduino_build_808351 -warnings=none -build-cache C:\Users\GIORGIOP\AppData\Local\Temp\arduino_cache_141 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=C:\Users\GIORGIOP\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.0.1-arduino2 -prefs=runtime.tools.avrdude-6.0.1-arduino2.path=C:\Users\GIORGIOP\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.0.1-arduino2 -prefs=runtime.tools.avr-gcc.path=C:\Users\GIORGIOP\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino2 -prefs=runtime.tools.avr-gcc-4.8.1-arduino2.path=C:\Users\GIORGIOP\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino2 -verbose C:\Users\GIORGIOP\AppData\Local\Temp\arduino_modified_sketch_540121\sketch_jan25a.ino
Using board 'nano' from platform in folder: C:\Users\GIORGIOP\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.6.2
Using core 'arduino' from platform in folder: C:\Users\GIORGIOP\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.6.2
WARNING: Category '' in library EEPROM is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library SPI is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library SoftwareSerial is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library Wire is not valid. Setting to 'Uncategorized'
Warning: platform.txt from core 'Arduino AVR Boards' contains deprecated recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{build.path}/{archive_file}" "{object_file}", automatically converted to recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{archive_file_path}" "{object_file}". Consider upgrading this core.
Detecting libraries used...
"C:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino2/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10808 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.6.2\\cores\\arduino" "-IC:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.6.2\\variants\\eightanaloginputs" "C:\\Users\\GIORGIOP\\AppData\\Local\\Temp\\arduino_build_808351\\sketch\\sketch_jan25a.ino.cpp" -o nul
"C:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino2/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10808 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.6.2\\cores\\arduino" "-IC:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.6.2\\variants\\eightanaloginputs" "-IC:\\Program Files (x86)\\Arduino\\libraries\\LiquidCrystal\\src" "C:\\Users\\GIORGIOP\\AppData\\Local\\Temp\\arduino_build_808351\\sketch\\sketch_jan25a.ino.cpp" -o nul
"C:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino2/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10808 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.6.2\\cores\\arduino" "-IC:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.6.2\\variants\\eightanaloginputs" "-IC:\\Program Files (x86)\\Arduino\\libraries\\LiquidCrystal\\src" "-IC:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.6.2\\libraries\\EEPROM" "C:\\Users\\GIORGIOP\\AppData\\Local\\Temp\\arduino_build_808351\\sketch\\sketch_jan25a.ino.cpp" -o nul
"C:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino2/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10808 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.6.2\\cores\\arduino" "-IC:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.6.2\\variants\\eightanaloginputs" "-IC:\\Program Files (x86)\\Arduino\\libraries\\LiquidCrystal\\src" "-IC:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.6.2\\libraries\\EEPROM" "C:\\Program Files (x86)\\Arduino\\libraries\\LiquidCrystal\\src\\LiquidCrystal.cpp" -o nul
Generating function prototypes...
"C:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino2/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10808 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.6.2\\cores\\arduino" "-IC:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.6.2\\variants\\eightanaloginputs" "-IC:\\Program Files (x86)\\Arduino\\libraries\\LiquidCrystal\\src" "-IC:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.6.2\\libraries\\EEPROM" "C:\\Users\\GIORGIOP\\AppData\\Local\\Temp\\arduino_build_808351\\sketch\\sketch_jan25a.ino.cpp" -o "C:\\Users\\GIORGIOP\\AppData\\Local\\Temp\\arduino_build_808351\\preproc\\ctags_target_for_gcc_minus_e.cpp"
"C:\\Program Files (x86)\\Arduino\\tools-builder\\ctags\\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\\Users\\GIORGIOP\\AppData\\Local\\Temp\\arduino_build_808351\\preproc\\ctags_target_for_gcc_minus_e.cpp"
Compiling sketch...
"C:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino2/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10808 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.6.2\\cores\\arduino" "-IC:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.6.2\\variants\\eightanaloginputs" "-IC:\\Program Files (x86)\\Arduino\\libraries\\LiquidCrystal\\src" "-IC:\\Users\\GIORGIOP\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.6.2\\libraries\\EEPROM" "C:\\Users\\GIORGIOP\\AppData\\Local\\Temp\\arduino_build_808351\\sketch\\sketch_jan25a.ino.cpp" -o "C:\\Users\\GIORGIOP\\AppData\\Local\\Temp\\arduino_build_808351\\sketch\\sketch_jan25a.ino.cpp.o"
C:\Users\GIORGIOP\AppData\Local\Temp\arduino_modified_sketch_540121\sketch_jan25a.ino: In member function 'void DSPL::init()':

sketch_jan25a:553:36: error: invalid conversion from 'const byte* {aka const unsigned char*}' to 'uint8_t* {aka unsigned char*}' [-fpermissive]

   LiquidCrystal::createChar(1, cent);

                                    ^

In file included from C:\Users\GIORGIOP\AppData\Local\Temp\arduino_modified_sketch_540121\sketch_jan25a.ino:1:0:

C:\Program Files (x86)\Arduino\libraries\LiquidCrystal\src/LiquidCrystal.h:81:8: error:   initializing argument 2 of 'void LiquidCrystal::createChar(uint8_t, uint8_t*)' [-fpermissive]

   void createChar(uint8_t, uint8_t[]);

        ^

Using library LiquidCrystal at version 1.0.7 in folder: C:\Program Files (x86)\Arduino\libraries\LiquidCrystal 
Using library EEPROM at version 2.0 in folder: C:\Users\GIORGIOP\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.6.2\libraries\EEPROM 
exit status 1
invalid conversion from 'const byte* {aka const unsigned char*}' to 'uint8_t* {aka unsigned char*}' [-fpermissive]

**Comment by DeshmukhMalhar** [comment]
try changing 
` const byte cent[8] `
to 
` const uint8_t cent[8] `

**Comment by giorgio-palma** [comment]
thank you so much now compile it out perfectly.
I had to change
"const byte cent[8]"
to
"uint8_t cent[8]"
