### ISSUE TITLE
mistake in pcb file

### ISSUE THREAD

**Issue by samsam1202** [ManojBR105/Soldering-Station#3]
hi dear Manoj

I tried to build your project.

https://github.com/ManojBR105/Soldering-Station

I think there was a mistake in your eagle PCB board.

the 5-volt positive input in the PCB is grounded and did not connect to anything.

please check the screenshot bellow:

https://imgur.com/a/DPOdkQ3

can you explain what can I do.

thanks

**Comment by ManojBR105** [comment]
Click on Ratnest icon it should fill the planes and you will be able to see connections.

**Comment by samsam1202** [comment]
> Click on Ratnest icon it should fill the planes and you will be able to see connections.
done. thanks

**Comment by samsam1202** [comment]
> Click on Ratnest icon it should fill the planes and you will be able to see connections.

done . thanks
